name: api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-267.0.dev

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.2.0-beta.7
  shared_preferences: ^2.3.3
  http: ">0.13.0 <2.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_lints: ^5.0.0
